S01 us14 contact
WildCodeSchool/orleans-202103-php-project-interim pull request #13
Opened 2021-06-04 09:13 UTC by maxime-guichard

2021-06-04 09:31 UTC, Wowlfy approved these changes

2021-06-04 09:32 UTC, Erdnaxela45 approved these changes

2021-06-08 12:12 UTC, LucyMerlier requested changes
see comments

2021-06-08 12:12 UTC, LucyMerlier commented on src/Form/ContactType.php
> +use Symfony\Component\Form\Extension\Core\Type\SubmitType;
why this use if you're not using it? => should not be there

2021-06-08 12:12 UTC, LucyMerlier commented on templates/emails/contact.html.twig
> +<h1>Nouveau contact</h1>
what is the point of this file? you are not using it => should be deleted

2021-06-08 12:12 UTC, LucyMerlier commented on templates/emails/contact.html.twig
> +<p>Message : {{ contact.message|raw }}</p>
NEVER USE RAW FILTER

2021-06-08 12:12 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +            $this->addFlash('message', 'Votre message a été transmis,
"message" is not a very good descriptor for tghis type of message, would better be "success" for example, since it indicates that the mail has successfully been sent

2021-06-08 12:12 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +        $form = $this->createForm(ContactType::class);
you did not instanciate a "Contact" object to be hydrated by your form

2021-06-08 12:12 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +        return $this->render('contact/index.html.twig', ['form' => $form->createView()]);
you should send a "Contact" object to your view

2021-06-08 12:12 UTC, LucyMerlier commented on templates/contact/index.html.twig
> +	{% endfor %}
ideally, this part should be in "base.html.twig", so that you can have access to flash messages from anywhere in the website

2021-06-08 12:12 UTC, LucyMerlier commented on templates/contact/index.html.twig
> +					{{ form_start(form) }}
you already started your form on line 20

2021-06-08 12:12 UTC, LucyMerlier commented on templates/contact/index.html.twig
> +					{{ form_start(form) }}
ideally should be in the div above (this is basically your opening form tag, so not part of the "form-group" on the same level of an input and label)

2021-06-08 20:00 UTC, maxime-guichard commented on composer.json
> +        "doctrine/doctrine-fixtures-bundle": "^3.3",
je vois pas le problème d'installer pour plus tard mais bon

2021-06-08 20:01 UTC, maxime-guichard commented on composer.lock
> +    "content-hash": "5f4af2cc5a3d2e3bc95e612ef6aa15d2",
Je sais pas ce que sais donc si tu veux

2021-06-08 20:02 UTC, maxime-guichard commented on composer.lock
> +            "version": "v5.2.10",
j'ai remis 7 on verra

2021-06-09 08:16 UTC, closed without merging