S02_US9 : Changed navbar style and fixed links
WildCodeSchool/orleans-202103-php-project-interim pull request #17
Opened 2021-06-08 13:54 UTC by Erdnaxela45

2021-06-08 14:11 UTC, maxime-guichard submitted a review, later dismissed

2021-06-09 08:06 UTC, LucyMerlier requested changes
see comments

2021-06-09 08:06 UTC, LucyMerlier commented on templates/base.html.twig
> +            {{ encore_entry_link_tags('navbar') }}
indentation

2021-06-09 08:06 UTC, LucyMerlier commented on templates/_navbar_student.html.twig
>          </ul>
wait, so this is the same navbar for companies and students after all?

2021-06-09 08:27 UTC, maxime-guichard approved these changes

2021-06-09 08:43 UTC, JuMn88 approved these changes

2021-06-09 08:47 UTC, LucyMerlier approved these changes

2021-06-09 08:47 UTC, merged