S01US14: Création du contact utilisateur
WildCodeSchool/orleans-202103-php-project-interim pull request #22
Opened 2021-06-09 10:17 UTC by maxime-guichard

2021-06-09 10:22 UTC, JuMn88 submitted a review, later dismissed

2021-06-09 11:50 UTC, LucyMerlier requested changes
see comments

2021-06-09 11:50 UTC, LucyMerlier commented on src/Entity/Contact.php
> +     * @Assert\Lenght(min=10)
typo : should be "Length" not "Lenght" + why 10 characters minimum? (=> you should not make validation for minimum length unless that is relevant)

2021-06-09 11:50 UTC, LucyMerlier commented on src/Form/ContactType.php
> +                    'placeholder' => 'Hubert'
do you plan on using this placeholder for your final website? if so, ok, if not, it should not be that way right now, because that would mean you will need to do a fix later just for that....

2021-06-09 11:50 UTC, LucyMerlier commented on src/Form/ContactType.php
> +                    'placeholder' => 'Bonisseur de La Bath'
same as above

2021-06-09 11:50 UTC, LucyMerlier commented on src/Form/ContactType.php
> +                    'placeholder' => 'oss117@gmail.com'
same as above

2021-06-09 11:50 UTC, LucyMerlier commented on templates/contact/index.html.twig
> +			</div>
indentation

2021-06-09 11:50 UTC, LucyMerlier commented on templates/base.html.twig
> +	</body>
indentation + don't mix tabs and spaces for indentation! choose one and use it for the whole document!

2021-06-09 13:31 UTC, maxime-guichard commented
Le fix a l'air de prendre le dessus sûr le reste

2021-06-09 13:50 UTC, JuMn88 approved these changes

2021-06-09 14:21 UTC, LucyMerlier requested changes
requested changes where not taken into consideration

2021-06-09 14:29 UTC, maxime-guichard commented on templates/base.html.twig
> +	</body>
j'ai que des tab

2021-06-09 14:32 UTC, Erdnaxela45 submitted a review, later dismissed

2021-06-10 07:14 UTC, LucyMerlier requested changes
see comments

2021-06-10 07:14 UTC, LucyMerlier commented on src/Entity/Contact.php
> +     * @Assert\Length(min=10)
don't do validations for minimum length => why 10 characters? why not 2 or 14 or 17? doing validations on minimum length does not make sense most of the time, including here

2021-06-10 09:11 UTC, JuMn88 approved these changes

2021-06-11 07:25 UTC, LucyMerlier requested changes

2021-06-11 07:28 UTC, JuMn88 approved these changes

2021-06-11 07:29 UTC, LucyMerlier approved these changes

2021-06-11 07:29 UTC, merged