Createaccount
WildCodeSchool/orleans-202103-php-project-interim pull request #26
Opened 2021-06-09 14:16 UTC by Wowlfy

2021-06-09 14:21 UTC, maxime-guichard approved these changes

2021-06-10 07:10 UTC, LucyMerlier requested changes
see comments

2021-06-10 07:10 UTC, LucyMerlier commented on src/Security/UserfixturesAuthenticator.php
> +class UserfixturesAuthenticator extends AbstractFormLoginAuthenticator implements PasswordAuthenticatedInterface
why does your authenticator have the word "fixtures" in its name?

2021-06-10 07:10 UTC, LucyMerlier commented on templates/security/login.html.twig
> +{% extends 'base.html.twig' %}
why does this extend base.html.twig directly?

2021-06-10 07:10 UTC, LucyMerlier commented on templates/security/login.html.twig
> +    #}
comments are good, but commented code is bad => leave no commented code in your files, even when it's auto-generated by Symfony

2021-06-11 09:06 UTC, maxime-guichard approved these changes

2021-06-14 09:20 UTC, LucyMerlier requested changes
see comments

2021-06-14 09:20 UTC, LucyMerlier commented on src/DataFixtures/UserFixtures.php
> +        $manager->persist($compagny);
in english : "company" => no "g"

2021-06-14 09:20 UTC, LucyMerlier commented on templates/security/login.html.twig
> +{% block title %}Log in!{% endblock %}
so, you website is gonna be in english after all?

2021-06-14 09:20 UTC, LucyMerlier commented on templates/security/login.html.twig
> +            You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
same as above

2021-06-14 09:20 UTC, LucyMerlier commented on templates/security/login.html.twig
> +    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
same as above

2021-06-14 09:20 UTC, LucyMerlier commented on templates/security/login.html.twig
> +    <label for="inputPassword">Password</label>
same as above

2021-06-14 09:20 UTC, LucyMerlier commented on templates/security/login.html.twig
> +        Sign in
same as above

2021-06-14 09:47 UTC, maxime-guichard approved these changes

2021-06-14 10:07 UTC, LucyMerlier requested changes

2021-06-14 10:07 UTC, LucyMerlier commented on templates/security/login.html.twig
> +            Tu es connecté en tant que  {{ app.user.username }}, <a href="{{ path('app_logout') }}">Deconnexion</a>
"Vous" may be better here + be inclusive ! ("connecté·e")

2021-06-15 07:20 UTC, Erdnaxela45 approved these changes

2021-06-15 08:29 UTC, LucyMerlier approved these changes

2021-06-15 08:29 UTC, merged