lister admin offre
WildCodeSchool/orleans-202103-php-project-interim pull request #28
Opened 2021-06-10 15:16 UTC by endricklosange

16 edit Do not worry, it's normal (crud)

2021-06-10 21:53 UTC, maxime-guichard submitted a review, later dismissed

2021-06-11 07:47 UTC, Erdnaxela45 approved these changes

2021-06-14 09:37 UTC, LucyMerlier requested changes
see comments

2021-06-14 09:37 UTC, LucyMerlier commented on src/Entity/Company.php
> +    private int $siret;
siret codes, just like postal codes or phone numbers, should be type string

2021-06-14 09:37 UTC, LucyMerlier commented on src/Entity/Job.php
> +    private DateTimeInterface $registereAt;
you missed a "d" => should be "$registeredAt"

2021-06-14 09:37 UTC, LucyMerlier commented on src/Entity/Job.php
> +     * @ORM\Column(type="string", length=200)
why 200? why not 255?

2021-06-14 09:37 UTC, LucyMerlier commented on src/Entity/Job.php
> +    private int $postalCode;
postal codes, just like siret codes or phone numbers, should be type string

2021-06-14 09:37 UTC, LucyMerlier commented on templates/admin_job/_form.html.twig
> +    <button class="btn">{{ button_label|default('Save') }}</button>
so your website is gonna be in english after all?

2021-06-14 09:37 UTC, LucyMerlier commented on templates/admin_job/_delete_form.html.twig
> +</form>
so your website is gonna be in english after all?

2021-06-14 09:37 UTC, LucyMerlier commented on templates/admin_job/edit.html.twig
> +{% endblock %}
so your website is gonna be in english after all?

2021-06-14 09:37 UTC, LucyMerlier commented on templates/admin_job/edit.html.twig
> +{% extends 'base.html.twig' %}
this template extends base.html.twig directly?

2021-06-14 09:37 UTC, LucyMerlier commented on templates/admin_job/index.html.twig
> +                        <p>{{ job.Description }}</p>
should not use PascalCase here for job properties => use camelCase (ex : "job.company.companyName")

2021-06-14 09:37 UTC, LucyMerlier commented on templates/base.html.twig
> +            {{ encore_entry_link_tags('adminJob') }}
so you will need the style for the admin job page on your whole website? this entry link should be included only on the page where you need it

2021-06-14 09:37 UTC, LucyMerlier commented on templates/base.html.twig
>  		{% endblock %}
indentation?

2021-06-14 09:37 UTC, LucyMerlier commented on src/Form/JobType.php
> +            ->add('company');
you should configure input types and labels here

2021-06-14 09:37 UTC, LucyMerlier commented on src/Entity/Company.php
> +    private Collection $jobs;
you should do all the validations on your class properties already (using @ Assert annotations)

2021-06-14 09:37 UTC, LucyMerlier commented on src/Entity/Job.php
> +    private ?Company $company;
you should do all the validations on your class properties already (using @ Assert annotations)

2021-06-15 07:21 UTC, Erdnaxela45 submitted a review, later dismissed

2021-06-15 08:44 UTC, LucyMerlier requested changes
see comments

2021-06-15 08:44 UTC, LucyMerlier commented on migrations/Version20210610162006.php
> +        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F8979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
:exclamation: you havce 2 migrations that create tables : this migration should not be here anymore :exclamation: 

=> if you wanna do modifications on your entities, either : 
 - do modifications in your entities files, and do another migration (which should then only contain "ALTER TABLE" type of requests

OR

 - do a new migration completely that will create tables correctly form the get-go (and that is what you did here), but then you HAVE TO delete the previous one (so in your case, this one)

2021-06-15 08:44 UTC, LucyMerlier commented on src/DataFixtures/JobFixtures.php
> +            }
it works, but you could have done this in one line : `$job->setCompany($this->getReference('company_' . rand(1, CompanyFixtures::LOOPNUMBER)))`

2021-06-15 08:44 UTC, LucyMerlier commented on src/Entity/Company.php
> +     * maxMessage = "La raison social ne peut pas dépasser {{ limit }} caractères")
"raison socialE"

2021-06-15 08:44 UTC, LucyMerlier commented on src/Entity/Company.php
> +     * @Assert\NotBlank(message="Veuillez remplir ce champ s'il vous plait .")
why put a period at the end of your NotBlank message when you don't end any of your other messages with a period?

2021-06-15 08:44 UTC, LucyMerlier commented on src/Form/JobType.php
> +                    'placeholder' => 'Saisir une code postal'
"UN code postal"

2021-06-15 08:44 UTC, LucyMerlier commented on templates/admin_job/_delete_form.html.twig
> +<form method="post" action="{{ path('admin_job_delete', {'id': job.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
your confirm message is still in english?

2021-06-15 08:44 UTC, LucyMerlier commented on templates/admin_job/edit.html.twig
> +	{{ include('admin_job/_form.html.twig', {'button_label': 'Update'}) }}
you button label is in english?

2021-06-15 08:44 UTC, LucyMerlier commented on templates/base.html.twig
> +
why add an empty line here?

2021-06-15 10:07 UTC, endricklosange commented on templates/admin_job/_delete_form.html.twig
> +<form method="post" action="{{ path('admin_job_delete', {'id': job.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
c'est en francais

2021-06-16 06:51 UTC, Erdnaxela45 approved these changes

2021-06-16 07:27 UTC, LucyMerlier requested changes
see comments

2021-06-16 07:27 UTC, LucyMerlier commented on src/Form/JobType.php
> +                'label' => 'Heure par semaine',
"heureS" => plural

2021-06-16 07:27 UTC, LucyMerlier commented on src/Form/JobType.php
> +            ]);
no label for this field?

2021-06-16 09:46 UTC, Erdnaxela45 approved these changes

2021-06-16 09:46 UTC, maxime-guichard approved these changes

2021-06-16 11:39 UTC, LucyMerlier approved these changes

2021-06-16 11:39 UTC, merged