US25: formulaire de demande de devis
WildCodeSchool/orleans-202103-php-project-interim pull request #29
Opened 2021-06-10 18:00 UTC by JuMn88

As a signed in company, I want to request a quotation:
-creating a form
-validate the fields' inputs
-displaying a message (needs US14)

2021-06-10 21:52 UTC, maxime-guichard approved these changes

2021-06-11 07:39 UTC, LucyMerlier requested changes
see comments

2021-06-11 07:39 UTC, LucyMerlier commented on src/Controller/CompanyController.php
> +            //Message de confirmation pour l'utilisateur
comments should be in english too

2021-06-11 07:39 UTC, LucyMerlier commented on src/Controller/CompanyController.php
> +            // Envoyer un mail
comments should be in english too

2021-06-11 07:39 UTC, LucyMerlier commented on src/Controller/CompanyController.php
> +                'message',
"message" is not the best category of flash message here, "success" may be better, since it indicates that a message has "successfully" been sent

2021-06-11 07:55 UTC, Erdnaxela45 approved these changes

2021-06-11 08:11 UTC, LucyMerlier approved these changes

2021-06-11 08:11 UTC, merged