fix assert
WildCodeSchool/orleans-202103-php-project-interim pull request #31
Opened 2021-06-11 08:11 UTC by maxime-guichard

2021-06-11 08:13 UTC, Erdnaxela45 submitted a review, later dismissed

2021-06-11 08:21 UTC, LucyMerlier requested changes
see comment

2021-06-11 08:21 UTC, LucyMerlier commented on src/Entity/assert
> +     */
what is this file doing here?

2021-06-11 08:25 UTC, Erdnaxela45 submitted a review, later dismissed

2021-06-11 09:24 UTC, LucyMerlier requested changes
see comment

2021-06-11 09:24 UTC, LucyMerlier commented on templates/component/_navbar.html.twig
> +                <a class="nav-link ms-5 me-5 active" href="/contact/index">Contact</a>
never put urls in hrefs, always use twig function path

2021-06-11 13:54 UTC, JuMn88 submitted a review, later dismissed

2021-06-14 09:59 UTC, LucyMerlier submitted a review, later dismissed

2021-06-15 07:22 UTC, Erdnaxela45 approved these changes

2021-06-15 08:27 UTC, LucyMerlier approved these changes

2021-06-15 08:27 UTC, merged