S02US10: modifiaction du style
WildCodeSchool/orleans-202103-php-project-interim pull request #37
Opened 2021-06-11 16:05 UTC by maxime-guichard

2021-06-14 07:22 UTC, Wowlfy submitted a review, later dismissed

2021-06-14 09:51 UTC, Wowlfy approved these changes

2021-06-14 10:03 UTC, LucyMerlier requested changes
see comments + lighten up those 3 images a bit (should be <200kb, especially for small icons like that)

2021-06-14 10:03 UTC, LucyMerlier commented on templates/component/_footer.html.twig
>  </footer>
wait, so you have 2 footers?

2021-06-14 10:03 UTC, LucyMerlier commented on templates/base/_footer.html.twig
> +</footer>
wait, so you have 2 footers?

2021-06-14 10:26 UTC, maxime-guichard commented on templates/base/_footer.html.twig
> +</footer>
c'est supprimé

2021-06-15 08:01 UTC, Erdnaxela45 submitted a review, later dismissed

2021-06-15 08:26 UTC, LucyMerlier requested changes
see comments

2021-06-15 08:26 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +		class="container pt-3">
why is this div's class attribute on the next line?

2021-06-15 08:26 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +			class="row py-3">
why is this div's class attribute on the next line?

2021-06-15 08:26 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +				class="col-lg-4 col-md-6 mb-4 mb-md-0">
why is this div's class attribute on the next line?

2021-06-15 08:26 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +					class="d-flex justify-content-around">
why is this section's class attribute on the next line?

2021-06-15 08:26 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +						</li>
you switch those link's hrefs (your contact link goes to the quotation request page and your quotation request link goes to your contact page)

2021-06-15 08:26 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +			</div>
indentation

2021-06-15 08:28 UTC, maxime-guichard commented on templates/component/_footer.html.twig
> +		class="container pt-3">
it's not my fault i press ctrl+maj+i

2021-06-15 08:29 UTC, maxime-guichard commented on templates/component/_footer.html.twig
> +			class="row py-3">
it's not my fault i press ctrl+maj+i

2021-06-15 08:29 UTC, maxime-guichard commented on templates/component/_footer.html.twig
> +				class="col-lg-4 col-md-6 mb-4 mb-md-0">
it's not my fault i press ctrl+maj+i

2021-06-15 08:29 UTC, maxime-guichard commented on templates/component/_footer.html.twig
> +					class="d-flex justify-content-around">
it's not my fault i press ctrl+maj+i

2021-06-15 08:29 UTC, maxime-guichard commented on templates/component/_footer.html.twig
> +			</div>
it's not my fault i press ctrl+maj+i

2021-06-15 08:39 UTC, endricklosange approved these changes

2021-06-15 09:19 UTC, LucyMerlier requested changes
see comments

2021-06-15 09:19 UTC, LucyMerlier commented on templates/component/_navbar_admin.html.twig
> +gt branch*<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
what is this "git branch" doing here?

2021-06-15 09:19 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +		class="container pt-3">
not my problem, fix it.

2021-06-15 09:19 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +			class="row py-3">
not my problem, fix it.

2021-06-15 09:19 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +				class="col-lg-4 col-md-6 mb-4 mb-md-0">
not my problem, fix it.

2021-06-15 09:19 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +					class="d-flex justify-content-around">
not my problem, fix it.

2021-06-15 09:55 UTC, Erdnaxela45 submitted a review, later dismissed

2021-06-15 10:11 UTC, LucyMerlier requested changes
see comments

2021-06-15 10:11 UTC, LucyMerlier commented on templates/component/_footer.html.twig
>  	class="bg-secondary text-center text-white">
forgot one => class attribute of footer should be on same line

2021-06-15 10:11 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +			class="col-lg-4 col-md-6 mb-4 mb-md-0 pt-2">
and another one => class attribute of div should be on same line

2021-06-15 10:11 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +				class="col-lg-4 col-md-6 mb-4 mb-md-0 pt-2">
and another one => class attribute of div should be on same line

2021-06-15 10:11 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +</div></footer>
why is this div closing tag on the same line as the footer closing tag? => check your number of divs, I suspect you have one too much div closing tag

2021-06-15 10:20 UTC, Erdnaxela45 submitted a review, later dismissed

2021-06-15 10:29 UTC, LucyMerlier requested changes
see comment

2021-06-15 10:29 UTC, LucyMerlier commented on templates/component/_footer.html.twig
> +			</section>
i guess you meant to close the div that you openned on line 37, not a section

2021-06-15 12:18 UTC, endricklosange approved these changes

2021-06-15 14:41 UTC, LucyMerlier approved these changes

2021-06-15 14:41 UTC, merged