Fix_navbar
WildCodeSchool/orleans-202103-php-project-interim pull request #38
Opened 2021-06-15 14:29 UTC by JuMn88

fixing the right path to Home in the navbar

2021-06-15 14:30 UTC, Erdnaxela45 approved these changes

2021-06-15 14:39 UTC, LucyMerlier requested changes

2021-06-15 14:39 UTC, LucyMerlier commented on templates/component/_navbar.html.twig
> +                <a class="nav-link ms-5 me-5 active" href="{{ path('accueil') }}">Accueil</a>
oh... sorry I did not catch that in HomeController, but the names of your routes should always be in english (just like the rest of your code), and only the urls themselves should be in french

=> "home" was alright, you should change it back to "home" in HomeController

2021-06-16 10:09 UTC, Erdnaxela45 approved these changes

2021-06-16 11:38 UTC, LucyMerlier approved these changes

2021-06-16 11:38 UTC, merged