US30 Mailer (Demande de devis)
WildCodeSchool/orleans-202103-php-project-interim pull request #48
Opened 2021-06-17 14:28 UTC by JuMn88

-Mailer setting
-Adding mailer in CompanyController (QuotationRequest)
-Creating a twig (quotationRequestEmail)
-Creating an email layout

2021-06-17 14:33 UTC, maxime-guichard approved these changes

2021-06-17 14:33 UTC, endricklosange submitted a review, later dismissed

2021-06-18 06:54 UTC, LucyMerlier requested changes
see comment

2021-06-18 06:54 UTC, LucyMerlier commented on templates/email/quotationRequestEmail.html.twig
> +    </p>
why is this table inside a p tag?

2021-06-18 08:12 UTC, Wowlfy approved these changes

2021-06-18 08:34 UTC, LucyMerlier approved these changes

2021-06-18 08:34 UTC, merged