S03_US04 Liste comptes Entreprise
WildCodeSchool/orleans-202103-php-project-interim pull request #54
Opened 2021-06-18 08:28 UTC by JuMn88

-creating relation OneToOne between User and Company
-updating UserFixtures
-new method in AdminController
-new template companiesList

2021-06-18 08:30 UTC, endricklosange submitted a review, later dismissed

2021-06-18 08:30 UTC, maxime-guichard submitted a review, later dismissed

2021-06-18 12:51 UTC, LucyMerlier requested changes
see comment

2021-06-18 12:51 UTC, LucyMerlier commented on src/Entity/User.php
> +    private string $phone;
honest question : it seems like you put this field as required (not nullable in DB) => is it intentional?

2021-06-18 12:51 UTC, LucyMerlier commented on templates/admin/companiesList.html.twig
> +                    </form>
it seems like this form is not used at all? => if it is not usable yet, just don't put it here

2021-06-18 13:05 UTC, JuMn88 commented on src/Entity/User.php
> +    private string $phone;
Yes

2021-06-18 23:00 UTC, maxime-guichard approved these changes

2021-06-21 09:51 UTC, LucyMerlier approved these changes

2021-06-21 09:52 UTC, merged