S03_US23 : Listed jobs for a single company
WildCodeSchool/orleans-202103-php-project-interim pull request #59
Opened 2021-06-21 13:45 UTC by Erdnaxela45

2021-06-21 13:51 UTC, maxime-guichard approved these changes

2021-06-21 13:54 UTC, JuMn88 approved these changes

2021-06-22 09:02 UTC, LucyMerlier requested changes
see comment

2021-06-22 09:02 UTC, LucyMerlier commented on src/Repository/JobRepository.php
> +use App\Entity\CompanyRepository;
you don't need this use statement here

2021-06-22 09:07 UTC, JuMn88 approved these changes

2021-06-22 09:38 UTC, LucyMerlier approved these changes

2021-06-22 09:38 UTC, merged