S04_US32 Liste des comptes Etudiants (côté admin)
WildCodeSchool/orleans-202103-php-project-interim pull request #62
Opened 2021-06-22 10:00 UTC by JuMn88

-creating student entity
-associated fixtures
-twig to list them (admin side)

2021-06-22 10:08 UTC, Erdnaxela45 approved these changes

2021-06-22 10:09 UTC, JuMn88 commented on templates/admin/students_list.html.twig
> +                            <h3>Lettre de motivation : {{ 'Lettre' }}</h3>
To be implemented in a further US

2021-06-23 12:03 UTC, LucyMerlier requested changes
see comments

2021-06-23 12:30 UTC, endricklosange submitted a review, later dismissed

2021-06-23 12:34 UTC, maxime-guichard submitted a review, later dismissed

2021-06-24 08:55 UTC, LucyMerlier approved these changes

2021-06-24 12:00 UTC, Erdnaxela45 approved these changes

2021-07-01 09:37 UTC, merged