bouton connexion/deconnexion
WildCodeSchool/orleans-202103-php-project-interim pull request #65
Opened 2021-06-22 13:15 UTC by Wowlfy

2021-06-22 13:25 UTC, maxime-guichard submitted a review, later dismissed

2021-06-23 07:22 UTC, LucyMerlier requested changes
see comment

2021-06-23 07:22 UTC, LucyMerlier commented on templates/component/_navbar.html.twig
> +                </li>
you have an extra closing li tag here (you close this li on line 33)

2021-06-23 14:00 UTC, Erdnaxela45 approved these changes

2021-06-24 08:54 UTC, LucyMerlier approved these changes

2021-06-24 08:54 UTC, merged