Init
WildCodeSchool/orleans-202103-php-project-interim pull request #7
Opened 2021-06-02 08:46 UTC by maxime-guichard

2021-06-02 13:25 UTC, endricklosange submitted a review, later dismissed

2021-06-02 13:25 UTC, Wowlfy approved these changes
oui

2021-06-02 14:35 UTC, LucyMerlier requested changes
see comments

2021-06-02 14:35 UTC, LucyMerlier commented on assets/styles/variables.scss
> +@import "~bootstrap/scss/bootstrap";
should not import bootstrap here (you already imported it in app.scss)

2021-06-02 14:35 UTC, LucyMerlier commented on assets/styles/app.scss
> +@import "~bootstrap/scss/bootstrap";
why use double quotes?

2021-06-02 14:35 UTC, LucyMerlier commented on templates/home/index.html.twig
>  {% block title %}Home{% endblock %}
so, your website will be in english?.. but you put a "lang=fr" attribute in your html tag?...

2021-06-02 14:35 UTC, LucyMerlier commented on templates/layout.html.twig
> +{% include '_navbar.html.twig' %}
you make an include of a file that does not exist => should delete this line

2021-06-03 08:25 UTC, JuMn88 approved these changes

2021-06-03 08:26 UTC, Wowlfy approved these changes

2021-06-03 08:39 UTC, LucyMerlier approved these changes

2021-06-03 08:39 UTC, merged