FIX_bdd: création de la constante domaine studyfield et du select studyfield
WildCodeSchool/orleans-202103-php-project-interim pull request #70
Opened 2021-06-23 12:08 UTC by maxime-guichard

2021-06-23 12:09 UTC, Erdnaxela45 submitted a review, later dismissed

2021-06-23 12:25 UTC, LucyMerlier requested changes
see comment

2021-06-23 12:25 UTC, LucyMerlier commented on src/DataFixtures/JobFixtures.php
> +            }
this just ends up giving the same study field to all your jobs => do a random like for the company?

2021-06-23 12:56 UTC, endricklosange approved these changes

2021-06-24 08:53 UTC, LucyMerlier requested changes
see comment

2021-06-24 08:53 UTC, LucyMerlier commented on src/DataFixtures/JobFixtures.php
> +                );
this rand should start at 0, and should not be inside a loop => just delete lines 31 and 35

2021-06-28 13:33 UTC, Erdnaxela45 approved these changes

2021-07-01 08:14 UTC, LucyMerlier requested changes
all this is also done in [this PR](https://github.com/WildCodeSchool/orleans-202103-php-project-interim/pull/78)

2021-07-01 10:21 UTC, closed without merging