barre de recherche admin entreprise
WildCodeSchool/orleans-202103-php-project-interim pull request #75
Opened 2021-06-24 13:21 UTC by endricklosange

2021-06-24 13:25 UTC, maxime-guichard approved these changes

2021-06-25 08:14 UTC, LucyMerlier requested changes
see comment

2021-06-25 08:14 UTC, LucyMerlier commented on src/Controller/AdminController.php
> +        $companies = $repository->findsearch($data);
"findSearch" => in camelCase

2021-06-25 09:59 UTC, maxime-guichard approved these changes

2021-07-01 08:22 UTC, LucyMerlier requested changes
see comments

2021-07-01 08:22 UTC, LucyMerlier commented on src/Data/SearchData.php
> +}
no getters and setters, just a public property?

2021-07-01 08:22 UTC, LucyMerlier commented on src/Form/SearchType.php
> +                'label' => false,
if you don't use a label, you should add an "aria-label" attribute to your input for accessibility

2021-07-01 12:43 UTC, JuMn88 approved these changes

2021-07-01 13:34 UTC, LucyMerlier approved these changes

2021-07-01 13:34 UTC, merged