S04 us11 filter offer
WildCodeSchool/orleans-202103-php-project-interim pull request #78
Opened 2021-06-26 07:34 UTC by maxime-guichard

2021-06-28 13:34 UTC, Erdnaxela45 submitted a review, later dismissed

2021-07-01 08:12 UTC, LucyMerlier requested changes
see comments

2021-07-01 08:12 UTC, LucyMerlier commented on src/DataFixtures/JobFixtures.php
> +            }
why use a loop here??

2021-07-01 08:12 UTC, LucyMerlier commented on src/Entity/FilterStudyField.php
> +     */
we actually don't need any assert here => my bad I must have been tired when I told you to do that

2021-07-01 08:12 UTC, LucyMerlier commented on templates/offer/index.html.twig
> +                {{ form_end(form) }}
indentation

2021-07-01 10:24 UTC, endricklosange approved these changes

2021-07-01 11:32 UTC, LucyMerlier approved these changes

2021-07-01 11:32 UTC, merged